apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - HostDevices
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: "1000:0097"
        resourceName: "dell.com/hba330"
      - pciVendorSelector: "8086:3902"
        resourceName: "optane.intel.com/900P"
      - pciVendorSelector: "8086:2700"
        resourceName: "optane.intel.com/900Psub"
      - pciVendorSelector: "144d:a808"
        resourceName: "nvme.samsung.com/970evo"
      - pciVendorSelector: "144d:a801"
        resourceName: "nvme.samsung.com/970sub"
      - pciVendorSelector: "10de:1c31"
        resourceName: "gpu.nvidia.com/P2200quadro"
      - pciVendorSelector: "10de:131b"
        resourceName: "gpu.nvidia.com/P2200sub"
      - pciVendorSelector: "10de:10f1"
        resourceName: "audio.nvidia.com/P2200quadro"
      - pciVendorSelector: "10de:131b"
        resourceName: "audio.nvidia.com/P2200sub"
      - pciVendorSelector: "1002:6995"
        resourceName: "vga.amd.com/wx2100pro"
      - pciVendorSelector: "1028:0b0c"
        resourceName: "vga.amd.com/wx2100sub"
      - pciVendorSelector: "1002:aae0"
        resourceName: "audio.amd.com/wx2100pro"
      - pciVendorSelector: "1028:aae0"
        resourceName: "audio.amd.com/wx2100sub"
#     - pciVendorSelector: "1c5c:1639"
#       resourceName: "sk.hynix.com/nvme512G"
  certificateRotateStrategy: {}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}