apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: f37microk8s 
  namespace: default
  labels:
    os: fedora
    app: microk8s
spec:
  dataVolumeTemplates:
  - metadata:
      name: fedora-k8s-volume-vda-root
      namespace: default
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          limits:
            storage: 128G
          requests:
            storage: 128G
        storageClassName: microk8s-hostpath
      source:
        registry:
          url: docker://docker.io/containercraft/fedora:latest
  running: true
  template:
    spec:
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            qemuGuestAgent:
              users:
              - usrbinkat
          source:
            secret:
              secretName: kargo-sshpubkey-kc2user
      domain:
        clock:
          timer: {}
          utc: {}
        cpu:
          cores: 1
          model: host-passthrough
          sockets: 2
          threads: 8
        devices:
          autoattachGraphicsDevice: true
          autoattachPodInterface: false
          autoattachSerialConsole: true
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: fedora-k8s-disk-vda-root
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            model: virtio
            name: enp1s0
          networkInterfaceMultiqueue: false
          rng: {}
        machine:
          type: q35
        resources:
          limits:
            memory: 32G
          requests:
            devices.kubevirt.io/kvm: "1"
            memory: 32G
      networks:
      - name: enp1s0
        multus:
          networkName: nadbr0
      terminationGracePeriodSeconds: 0
      volumes:
      - name: fedora-k8s-disk-vda-root
        dataVolume:
          name: fedora-k8s-volume-vda-root
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp1s0:
                dhcp4: true
                dhcp6: true
                dhcp-identifier: mac
          userData: |
            #cloud-config
            hostname: fedora
            ssh_pwauth: true
            disable_root: true
            chpasswd:
              list: |
                usrbinkat:usrbinkat
              expire: False
            users:
              - name: usrbinkat
                shell: /bin/bash
                lock_passwd: false
                sudo: ['ALL=(ALL) NOPASSWD:ALL']
                groups: sudo,libvirt,xrdp,docker,ssl-cert
            growpart:
              mode: auto
              devices: ['/']
              ignore_growroot_disabled: true
            package_upgrade: true
            packages:
              - "vim"
              - "snapd"
              - "screenfetch"
              - "qemu-guest-agent"
            runcmd:
              - "mkdir -p /home/usrbinkat/.ssh"
              - "chown -R usrbinkat:usrbinkat /home/usrbinkat/.ssh"
              - "mkdir -p /home/usrbinkat/.kube"
              - "chown -R usrbinkat:usrbinkat /home/usrbinkat/.kube"
              - "systemctl enable --now qemu-guest-agent"
              - "systemctl restart qemu-guest-agent"
              - "dnf remove -y pcsc-lite"
              - "systemctl stop firewalld"
              - "systemctl disable firewalld"
              - "screenfetch"
              - "/bin/fedora-third-party enable"
              - "sleep 30"
              - "ln -s /var/lib/snapd/snap /snap"
              - "snap install microk8s --classic"
