apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: us-west-1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.243.0.0/16
    services:
      cidrBlocks:
      - 10.95.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: us-west-1-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtCluster
    name: us-west-1
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: us-west-1
  namespace: default
spec:
  controlPlaneServiceTemplate:
    spec:
      type: LoadBalancer
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: us-west-1-control-plane
  namespace: default
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: default
        spec:
          runStrategy: Always
          dataVolumeTemplates:
          - metadata:
              name: capi-cp-volume
              namespace: default
            spec:
              pvc:
                storageClassName: truenas-optane-nfs
                accessModes:
                - ReadWriteOnce
                resources:
                  limits:
                    storage: 32G
                  requests:
                    storage: 32G
              source:
                registry:
                  url: docker://quay.io/capk/ubuntu-2004-container-disk:v1.23.10
          template:
            spec:
              accessCredentials:
              - sshPublicKey:
                  source:
                    secret:
                      secretName: kargo-sshpubkey-kc2user
                  propagationMethod:
                    qemuGuestAgent:
                      users:
                      - root
              domain:
                cpu:
                  cores: 1
                  threads: 6
                  model: host-passthrough
                devices:
                  autoattachSerialConsole: true
                  disks:
                  - name: capi-cp-disk
                    bootOrder: 1
                    disk:
                      bus: virtio
                memory:
                  guest: 8Gi
              evictionStrategy: External
              volumes:
              - name: capi-cp-disk
                dataVolume:
                  name: capi-cp-volume
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: us-west-1-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      networking:
        dnsDomain: us-west-1.capi.home.arpa
        podSubnet: 10.243.0.0/16
        serviceSubnet: 10.95.0.0/16
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtMachineTemplate
      name: us-west-1-control-plane
      namespace: default
  replicas: 3
  version: v1.23.10
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: us-west-1-md-0
  namespace: default
spec:
  template:
    spec:
      virtualMachineTemplate:
        metadata:
          namespace: default
        spec:
          runStrategy: Always
          dataVolumeTemplates:
          - metadata:
              name: capi-md-volume
              namespace: default
            spec:
              pvc:
                storageClassName: truenas-optane-nfs
                accessModes:
                - ReadWriteOnce
                resources:
                  limits:
                    storage: 32G
                  requests:
                    storage: 32G
              source:
                registry:
                  url: docker://quay.io/capk/ubuntu-2004-container-disk:v1.23.10
          template:
            spec:
              accessCredentials:
              - sshPublicKey:
                  source:
                    secret:
                      secretName: kargo-sshpubkey-kc2user
                  propagationMethod:
                    qemuGuestAgent:
                      users:
                      - root
              domain:
                cpu:
                  cores: 1
                  threads: 16
                  model: host-passthrough
                memory:
                  guest: 16Gi
                devices:
                  autoattachSerialConsole: true
                  disks:
                  - name: capi-md-disk
                    bootOrder: 1
                    disk:
                      bus: virtio
              evictionStrategy: External
              volumes:
              - name: capi-md-disk
                dataVolume:
                  name: capi-md-volume
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: us-west-1-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: us-west-1-md-0
  namespace: default
spec:
  clusterName: us-west-1
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: us-west-1-md-0
          namespace: default
      clusterName: us-west-1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KubevirtMachineTemplate
        name: us-west-1-md-0
        namespace: default
      version: v1.23.10
