#  - helm repo add metallb https://metallb.github.io/metallb && helm repo update
#  - helm upgrade --install metallb metallb/metallb --create-namespace --namespace metallb --values ./values.yaml

# values.yaml
controller:
  enabled: true
speaker:
  enabled: true
  tolerateMaster: true
crds:
  enabled: true
  validationFailurePolicy: Fail
