#  - helm repo add TrueCharts https://charts.truecharts.org && helm repo update
#  - helm upgrade --install ddns-updater TrueCharts/ddns-updater --create-namespace --namespace ddclient --values ./values.yaml
image:
  repository: tccr.io/truecharts/ddns-updater
  tag: v2.4.1@sha256:da6249fc9b5d1fbedfc4a4d7f0ed0bcff8c0742c54449c9f4b375fa55b7d98fe
  pullPolicy: IfNotPresent

env:
  TZ: "America/Los Angeles"
  LISTENING_PORT: "{{ .Values.service.main.ports.main.port }}"
  CONFIG: '{"settings":[{"provider":"dnsomatic","domain":"myip.dnsomatic.com","host":"home.usrbinkat.io","username":"kathryn.morgan@braincraft.io","password":"xxxxxxxxxxxxxxxxxxxxxxxxx","ip_version":"ipv4"}]}'
  PERIOD: "5m"
  IPV6_PREFIX: "/128"
  PUBLICIP_FETCHERS: "all"
  PUBLICIP_HTTP_PROVIDERS: "all"
  PUBLICIPV4_HTTP_PROVIDERS: "all"
  PUBLICIPV6_HTTP_PROVIDERS: "all"
  PUBLICIP_DNS_PROVIDERS: "all"
  PUBLICIP_DNS_TIMEOUT: "3s"
  UPDATE_COOLDOWN_PERIOD: "5m"
  HTTP_TIMEOUT: "10s"
  BACKUP_PERIOD: "0"
  LOG_LEVEL: "info"
  LOG_CALLER: "hidden"
  SHOUTRRR_ADDRESSES: ""

service:
  main:
    ports:
      main:
        port: 10227

persistence:
  data:
    enabled: true
    mountPath: "/updater/data"

portal:
  enabled: true

