---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  resources:
    requests:
      storage: 12G
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  resources:
    requests:
      storage: 256G
  accessModes:
  - ReadWriteOnce
