---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky
  namespace: dns
  labels:
    app: blocky
  annotations:
    app: blocky
data:
  config.yaml: |-
    upstream:
      default:
        - 192.168.1.23
        - 192.168.1.23
    blocking:
      processingConcurrency: 8
      blackLists:
        # https://firebog.net/
        ads:
          - https://adaway.org/hosts.txt
          - https://v.firebog.net/hosts/AdguardDNS.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
        sus:
          - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
          - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
          - https://v.firebog.net/hosts/static/w3kbl.txt
        extra:
          - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
        malicious:
          - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
          - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
          - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
          - https://v.firebog.net/hosts/Prigent-Crypto.txt
          - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
          - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
          - https://phishing.army/download/phishing_army_blocklist_extended.txt
          - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
          - https://v.firebog.net/hosts/RPiList-Phishing.txt
          - https://v.firebog.net/hosts/RPiList-Malware.txt
          - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
          - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
          - https://urlhaus.abuse.ch/downloads/hostfile/
        trackers:
          - https://v.firebog.net/hosts/Easyprivacy.txt
          - https://v.firebog.net/hosts/Prigent-Ads.txt
          - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
          - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      # adult: []
      clientGroupsBlock:
        default:
          - ads
          - sus
          - trackers
          - malicious
          - extra
          - adult
    httpPort: 4000
    port: 53
    logLevel: info
    caching:
      minTime: 5m
      maxTime: 30m
      maxItemsCount: 2000
      prefetching: true
      prefetchExpires: 2h
      prefetchThreshold: 5
      prefetchMaxItemsCount: 2000
      cacheTimeNegative: 30m
    bootstrapDns:
      ips:
      - 1.1.1.1
      - 1.0.0.1
    prometheus:
      enable: false
      path: /metrics
