---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  namespace: dns
  annotations:
    app: blocky
  labels:
    app: blocky
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ddclient-opendns
  template:
    metadata:
      labels:
        app: ddclient-opendns
        app.kubernetes.io/instance: blocky
        app.kubernetes.io/name: blocky
    spec:
      containers:
        - name: dns
          image: docker.io/spx01/blocky:v0.19
          imagePullPolicy: Always
          args:
          - sh
          - -c
          - /app/blocky --config /etc/blocky/config.yaml
          env:
          - name: TZ
            value: America/Los Angeles
          ports:
          - name: dns-tcp
            protocol: TCP
            containerPort: 53
          - name: dns-udp
            protocol: UDP
            containerPort: 53
          - name: blocky
            containerPort: 4000
            protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 256M
            limits:
              cpu: 200m
              memory: 256M
          securityContext:
            capabilities:
              drop:
              - CAP_MKNOD
              - CAP_NET_RAW
              - CAP_AUDIT_WRITE
          volumeMounts:
            - mountPath: /etc/blocky
              name: blocky-config
      volumes:
        - name: blocky-config
          configMap:
            defaultMode: 420
            name: blocky
            items:
            - key: config.yaml
              path: config.yaml
