apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: braincraft.io
  namespace: ingress
spec:
  secretName: braincraft-letsencrypt-wildcard
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "braincraft.io"
  - "*.braincraft.io"
