apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-survival-data
  namespace: minecraft
  labels:
    data: data
    app: minecraft
    medium: optane
spec:
  storageClassName: truenas-optane-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 12Gi
  accessModes:
  - ReadWriteMany
