apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-survival
  namespace: minecraft
  labels:
    app: minecraft-survival
spec:
  storageClassName: truenas-flash-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 12Gi
  accessModes:
  - ReadWriteOnce
